package models;

import java.io.Serializable;

public enum Actions implements Serializable{
	LOGIN,
	CREATE_ORDER,
	CREATE_ORDER_NOW,
	UPDATE_ORDER,
	READ_ORDER,
	READ_ALL_ORDERS,
	DELETE_ORDER,
	CREATE_CUSTOMER,
	UPDATE_CUSTOMER,
	UPDATE_CUSTOMER_BALANCE,
	READ_CUSTOMER,
	READ_ALL_CUSTOMERS,
	DELETE_CUSTOMER,
	CREATE_EMPLOYEE,
	UPDATE_EMPLOYEE,
	READ_EMPLOYEE,
	READ_ALL_EMPLOYEES,
	DELETE_EMPLOYEE,
	CREATE_ITEM,
	UPDATE_ITEM,
	READ_ITEM,
	READ_ALL_ITEMS,
	DELETE_ITEM,
	ADD_ITEM_TO_ORDER,
	READ_ORDERED_ITEMS,
	UPDATE_ORDERED_ITEM,
	DELETE_ITEM_FROM_ORDER,
	DELETE_ALL_ORDERED_ITEMS,
	VALIDATE_PASSWORD,
	UPDATE_PASSWORD,
	DELETE_PASSWORD
}
